Create app Poll
millad90s/webDict pull request #22
Opened 2023-07-01 23:40 UTC by aliskycloud

Milad, Plz chk task
Sepehr, Check the poll_info.html file in the templates directory

2023-07-02 21:59 UTC, millad90s commented on firstapp/firstapp/settings.py
> +
empty lines !!

2023-07-02 22:00 UTC, millad90s commented on firstapp/polls/models.py
> +
search about __str__ in python !

2023-07-02 22:01 UTC, millad90s commented on firstapp/polls/views.py
> +    return HttpResponse('Hello poll')
do we need this function !

2023-07-02 22:01 UTC, millad90s requested changes

2023-07-02 22:01 UTC, millad90s commented on firstapp/polls/views.py
> +    return render(request, 'poll_info.html')
what is it for ?

2023-07-02 23:38 UTC, aliskycloud commented
@millad90s 
@Sepii84 
I pushed again after the corrections

2023-07-03 08:41 UTC, Sepii84 commented
The Html file is all good as far as I can see

2023-07-03 21:05 UTC, merged